version: "3.7"

services:
    db:
        image: mysql:8.1.0
        container_name: mysql-db
        env_file:
            - .env
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "${DB_PORT}:3306"
